language: node_js

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker-compose -f ./docker-compose-build.yaml build --parallel

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  # Tagging 
  - docker tag udagram-api-feed comurule/udagram-api-feed:v3
  - docker tag udagram-api-user comurule/udagram-api-user:v3
  - docker tag udagram-frontend:local comurule/udagram-frontend:v3
  - docker tag reverseproxy comurule/reverseproxy:v3
  
  # Push
  - docker push comurule/udagram-frontend:v3
  - docker push comurule/udagram-api-feed:v3
  - docker push comurule/udagram-api-user:v3
  - docker push comurule/reverseproxy:v3

